import { test, expect } from '@playwright/test';

// Auto-generated Playwright test cases
// Generated by Test Case Generator Agent

// TC_FUNCTIONAL_001 - Successful User Sign Up with Valid Data



test('TC_FUNCTIONAL_001 - Successful User Sign Up with Valid Data', async ({ page }) => {
    await page.goto('/signup'); // Assuming the signup page is at '/signup'

    // Fill in valid and unique data
    await page.fill('input[name="email"]', 'unique.user@example.com');
    await page.fill('input[name="username"]', 'ValidUser123');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Click the Sign Up button
    await page.click('button[type="submit"]');

    // Wait for potential navigation or loading indicator
    await page.waitForNavigation();

    // Assertions for success message and redirection
    await expect(page).toHaveURL('/email-verification'); // Assuming redirection to email verification page
    await expect(page.locator('.success-message')).toBeVisible(); // Assuming a class for success message
    await expect(page.locator('.success-message')).toHaveText('Registration successful! Please check your email for verification.'); // Assuming specific success message
});


// TC_FUNCTIONAL_002 - Email Field - Required Validation



test('TC_FUNCTIONAL_002 - Email Field - Required Validation', async ({ page }) => {
    await page.goto('/signup');

    // Leave email field empty
    await page.fill('input[name="username"]', 'TestUser');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="email"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="email"] + .error-message')).toHaveText('Email is required.');
    await expect(page).not.toHaveURL('/email-verification'); // Ensure no redirection
});


// TC_FUNCTIONAL_003 - Email Field - Invalid Email Format Validation



test('TC_FUNCTIONAL_003 - Email Field - Invalid Email Format Validation', async ({ page }) => {
    await page.goto('/signup');

    // Fill with invalid email format
    await page.fill('input[name="email"]', 'invalid-email');
    await page.fill('input[name="username"]', 'TestUser');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="email"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="email"] + .error-message')).toHaveText('Please enter a valid email address.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_004 - Email Field - Already Exists Validation



test('TC_FUNCTIONAL_004 - Email Field - Already Exists Validation', async ({ page }) => {
    await page.goto('/signup');

    // Fill with an existing email
    await page.fill('input[name="email"]', 'existing.user@example.com');
    await page.fill('input[name="username"]', 'NewUser');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="email"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="email"] + .error-message')).toHaveText('Email address already in use.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_005 - Username Field - Required Validation



test('TC_FUNCTIONAL_005 - Username Field - Required Validation', async ({ page }) => {
    await page.goto('/signup');

    // Leave username field empty
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="username"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="username"] + .error-message')).toHaveText('Username is required.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_006 - Username Field - Minimum Length Validation (5 characters)



test('TC_FUNCTIONAL_006 - Username Field - Minimum Length Validation (5 characters)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with username less than 6 characters
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="username"]', 'User'); // 4 characters
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="username"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="username"] + .error-message')).toHaveText('Username must be between 6 and 20 alphanumeric characters.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_007 - Username Field - Maximum Length Validation (21 characters)



test('TC_FUNCTIONAL_007 - Username Field - Maximum Length Validation (21 characters)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with username more than 20 characters
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="username"]', 'ThisIsAVeryLongUsername123'); // 25 characters
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="username"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="username"] + .error-message')).toHaveText('Username must be between 6 and 20 alphanumeric characters.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_008 - Username Field - Non-Alphanumeric Characters Validation



test('TC_FUNCTIONAL_008 - Username Field - Non-Alphanumeric Characters Validation', async ({ page }) => {
    await page.goto('/signup');

    // Fill with non-alphanumeric characters
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="username"]', 'User-Name!');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="username"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="username"] + .error-message')).toHaveText('Username must be between 6 and 20 alphanumeric characters.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_009 - Username Field - Already Exists Validation



test('TC_FUNCTIONAL_009 - Username Field - Already Exists Validation', async ({ page }) => {
    await page.goto('/signup');

    // Fill with an existing username
    await page.fill('input[name="email"]', 'new.user@example.com');
    await page.fill('input[name="username"]', 'existinguser');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="username"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="username"] + .error-message')).toHaveText('Username already in use.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_010 - Password Field - Required Validation



test('TC_FUNCTIONAL_010 - Password Field - Required Validation', async ({ page }) => {
    await page.goto('/signup');

    // Leave password field empty
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="username"]', 'TestUser');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="password"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="password"] + .error-message')).toHaveText('Password is required.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_011 - Password Field - Minimum Length Validation (7 characters)



test('TC_FUNCTIONAL_011 - Password Field - Minimum Length Validation (7 characters)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with password less than 8 characters
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="username"]', 'TestUser');
    await page.fill('input[name="password"]', 'P@ss1'); // 5 characters
    await page.fill('input[name="confirmPassword"]', 'P@ss1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="password"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="password"] + .error-message')).toHaveText('Password must be at least 8 characters long and meet complexity requirements.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_012 - Password Field - Missing Uppercase Letter



test('TC_FUNCTIONAL_012 - Password Field - Missing Uppercase Letter', async ({ page }) => {
    await page.goto('/signup');

    // Fill with password missing uppercase
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="username"]', 'TestUser');
    await page.fill('input[name="password"]', 'password123!');
    await page.fill('input[name="confirmPassword"]', 'password123!');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="password"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="password"] + .error-message')).toHaveText('Password must contain at least one uppercase letter.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_013 - Password Field - Missing Lowercase Letter



test('TC_FUNCTIONAL_013 - Password Field - Missing Lowercase Letter', async ({ page }) => {
    await page.goto('/signup');

    // Fill with password missing lowercase
    await page.fill('input[name="email"]', 'test@example.com');
    await page.fill('input[name="username"]', 'TestUser');
    await page.fill('input[name="password"]', 'PASSWORD123!');
    await page.fill('input[name="confirmPassword"]', 'PASSWORD123!');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assertions for inline error message
    await expect(page.locator('input[name="password"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="password"] + .error-message')).toHaveText('Password must contain at least one lowercase letter.');
    await expect(page).not.toHaveURL('/email-verification');
});


// TC_FUNCTIONAL_014 - Password Field - Missing Number

test('TC_FUNCTIONAL_024 - Form does not submit if client-side validation fails', async ({ page }) => {
    await page.goto('/signup');

    // Intentionally cause client-side validation to fail
    await page.fill('input[name="email"]', 'invalid-email-format');
    await page.fill('input[name="username"]', 'Short'); // Too short
    await page.fill('input[name="password"]', 'weak'); // Not complex enough
    await page.fill('input[name="confirmPassword"]', 'weak'); // Mismatched
    // Terms & Conditions not checked

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Assert that the page has not navigated away
    await expect(page).toHaveURL('/signup');

    // Assert that multiple error messages are visible
    await expect(page.locator('input[name="email"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="username"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="password"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="confirmPassword"] + .error-message')).toBeVisible();
    await expect(page.locator('input[name="termsAndConditions"] + .error-message')).toBeVisible();
});


// TC_FUNCTIONAL_025 - Password Complexity - All requirements met



test('TC_FUNCTIONAL_025 - Password Complexity - All requirements met', async ({ page }) => {
    await page.goto('/signup');

    const validPassword = 'ComplexP@sswOrd1'; // Uppercase, lowercase, number, special char, >8 chars

    // Fill in valid data including a complex password
    await page.fill('input[name="email"]', 'complex.password@example.com');
    await page.fill('input[name="username"]', 'ComplexPassUser');
    await page.fill('input[name="password"]', validPassword);
    await page.fill('input[name="confirmPassword"]', validPassword);
    await page.click('input[name="termsAndConditions"]');

    // Click the Sign Up button
    await page.click('button[type="submit"]');

    // Wait for navigation and assert success
    await page.waitForNavigation();
    await expect(page).toHaveURL('/email-verification');
    await expect(page.locator('.success-message')).toBeVisible();
});


// TC_FUNCTIONAL_026 - Username Field - Boundary Value Test (6 characters)



test('TC_FUNCTIONAL_026 - Username Field - Boundary Value Test (6 characters)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with a username exactly 6 characters long
    await page.fill('input[name="email"]', 'boundary.user.6@example.com');
    await page.fill('input[name="username"]', 'User6'); // 6 characters
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Wait for navigation to confirm it's accepted
    await page.waitForNavigation();

    // Assertions for success
    await expect(page).toHaveURL('/email-verification');
    await expect(page.locator('.success-message')).toBeVisible();
});


// TC_FUNCTIONAL_027 - Username Field - Boundary Value Test (20 characters)



test('TC_FUNCTIONAL_027 - Username Field - Boundary Value Test (20 characters)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with a username exactly 20 characters long
    await page.fill('input[name="email"]', 'boundary.user.20@example.com');
    await page.fill('input[name="username"]', 'UserTwentyCharsLong'); // 20 characters
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Wait for navigation to confirm it's accepted
    await page.waitForNavigation();

    // Assertions for success
    await expect(page).toHaveURL('/email-verification');
    await expect(page.locator('.success-message')).toBeVisible();
});


// TC_FUNCTIONAL_028 - Password Field - Boundary Value Test (8 characters)



test('TC_FUNCTIONAL_028 - Password Field - Boundary Value Test (8 characters)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with a password exactly 8 characters long meeting complexity
    await page.fill('input[name="email"]', 'boundary.pass.8@example.com');
    await page.fill('input[name="username"]', 'BoundaryPass8');
    await page.fill('input[name="password"]', 'P@ss1234'); // 8 chars, meets complexity
    await page.fill('input[name="confirmPassword"]', 'P@ss1234');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Wait for navigation to confirm it's accepted
    await page.waitForNavigation();

    // Assertions for success
    await expect(page).toHaveURL('/email-verification');
    await expect(page.locator('.success-message')).toBeVisible();
});


// TC_FUNCTIONAL_029 - Email Field - Valid but unusual characters (e.g., with plus sign)



test('TC_FUNCTIONAL_029 - Email Field - Valid but unusual characters (e.g., with plus sign)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with a valid email format including a plus sign
    await page.fill('input[name="email"]', 'test+alias@example.com');
    await page.fill('input[name="username"]', 'PlusAliasUser');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Wait for navigation to confirm it's accepted
    await page.waitForNavigation();

    // Assertions for success
    await expect(page).toHaveURL('/email-verification');
    await expect(page.locator('.success-message')).toBeVisible();
});


// TC_FUNCTIONAL_030 - Username Field - Alphanumeric characters only (letters and numbers)



test('TC_FUNCTIONAL_030 - Username Field - Alphanumeric characters only (letters and numbers)', async ({ page }) => {
    await page.goto('/signup');

    // Fill with a username containing only letters and numbers
    await page.fill('input[name="email"]', 'alphanum.user@example.com');
    await page.fill('input[name="username"]', 'AlphaNumericUser123');
    await page.fill('input[name="password"]', 'P@sswOrd1');
    await page.fill('input[name="confirmPassword"]', 'P@sswOrd1');
    await page.click('input[name="termsAndConditions"]');

    // Attempt to submit
    await page.click('button[type="submit"]');

    // Wait for navigation to confirm it's accepted
    await page.waitForNavigation();

    // Assertions for success
    await expect(page).toHaveURL('/email-verification');
    await expect(page.locator('.success-message')).toBeVisible();
});


// TC_UI_001 - Verify presence and visibility of Email input field
test('TC_UI_001 - Verify presence and visibility of Email input field', async ({ page }) => {
    await page.goto('http://localhost:3000/signup'); // Assuming signup page is at this URL
    await expect(page.locator('[data-testid="email-input"]')).toBeVisible();
});

// TC_UI_002 - Verify presence and visibility of Username input field
test('TC_UI_002 - Verify presence and visibility of Username input field', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await expect(page.locator('[data-testid="username-input"]')).toBeVisible();
});

// TC_UI_003 - Verify presence and visibility of Password input field
test('TC_UI_003 - Verify presence and visibility of Password input field', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await expect(page.locator('[data-testid="password-input"]')).toBeVisible();
});

// TC_UI_004 - Verify presence and visibility of Confirm Password input field
test('TC_UI_004 - Verify presence and visibility of Confirm Password input field', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await expect(page.locator('[data-testid="confirm-password-input"]')).toBeVisible();
});

// TC_UI_005 - Verify presence and visibility of Sign Up button
test('TC_UI_005 - Verify presence and visibility of Sign Up button', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await expect(page.locator('[data-testid="signup-button"]')).toBeVisible();
});

// TC_UI_006 - Verify presence and visibility of Terms & Conditions checkbox
test('TC_UI_006 - Verify presence and visibility of Terms & Conditions checkbox', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await expect(page.locator('[data-testid="terms-checkbox"]')).toBeVisible();
});

// TC_UI_007 - Verify Email input field accepts valid email format
test('TC_UI_007 - Verify Email input field accepts valid email format', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'test@example.com');
    await expect(page.locator('[data-testid="email-input"]')).toHaveValue('test@example.com');
});

// TC_UI_008 - Verify Email input field shows error for invalid email format (missing @)
test('TC_UI_008 - Verify Email input field shows error for invalid email format (missing @)', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'testexample.com');
    await page.click('[data-testid="signup-button"]'); // Trigger validation
    await expect(page.locator('[data-testid="email-error-message"]')).toBeVisible();
    await expect(page.locator('[data-testid="email-error-message"]')).toHaveText('Invalid email format.');
});

// TC_UI_009 - Verify Email input field shows error for invalid email format (missing domain)
test('TC_UI_009 - Verify Email input field shows error for invalid email format (missing domain)', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'test@');
    await page.click('[data-testid="signup-button"]'); // Trigger validation
    await expect(page.locator('[data-testid="email-error-message"]')).toBeVisible();
    await expect(page.locator('[data-testid="email-error-message"]')).toHaveText('Invalid email format.');
});

// TC_UI_010 - Verify Email input field shows error for empty input
test('TC_UI_010 - Verify Email input field shows error for empty input', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', '');
    await page.click('[data-testid="signup-button"]'); // Trigger validation
    await expect(page.locator('[data-testid="email-error-message"]')).toBeVisible();
    await expect(page.locator('[data-testid="email-error-message"]')).toHaveText('Email is required.');
});

// TC_UI_011 - Verify Username input field accepts alphanumeric characters within length limits (6-20)
test('TC_UI_011 - Verify Username input field accepts alphanumeric characters within length limits (6-20)', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    const validUsername = 'validuser123'; // 12 characters
    await page.fill('[data-testid="username-input"]', validUsername);
    await expect(page.locator('[data-testid="username-input"]')).toHaveValue(validUsername);
});

// TC_UI_021 - Verify Confirm Password input field shows error when passwords do not match
test('TC_UI_021 - Verify Confirm Password input field shows error when passwords do not match', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    const password = 'Password1!';
    await page.fill('[data-testid="password-input"]', password);
    await page.fill('[data-testid="confirm-password-input"]', 'DifferentPass1!');
    await page.click('[data-testid="signup-button"]'); // Trigger validation
    await expect(page.locator('[data-testid="confirm-password-error-message"]')).toBeVisible();
    await expect(page.locator('[data-testid="confirm-password-error-message"]')).toHaveText('Passwords do not match.');
});

// TC_UI_022 - Verify Confirm Password input field accepts matching password
test('TC_UI_022 - Verify Confirm Password input field accepts matching password', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    const password = 'Password1!';
    await page.fill('[data-testid="password-input"]', password);
    await page.fill('[data-testid="confirm-password-input"]', password);
    await expect(page.locator('[data-testid="confirm-password-input"]')).toHaveValue(password);
});

// TC_UI_023 - Verify Confirm Password input field shows error for empty input
test('TC_UI_023 - Verify Confirm Password input field shows error for empty input', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="confirm-password-input"]', '');
    await page.click('[data-testid="signup-button"]'); // Trigger validation
    await expect(page.locator('[data-testid="confirm-password-error-message"]')).toBeVisible();
    await expect(page.locator('[data-testid="confirm-password-error-message"]')).toHaveText('Confirm Password is required.');
});

// TC_UI_024 - Verify Terms & Conditions checkbox is unchecked by default
test('TC_UI_024 - Verify Terms & Conditions checkbox is unchecked by default', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await expect(page.locator('[data-testid="terms-checkbox"]')).not.toBeChecked();
});

// TC_UI_025 - Verify Sign Up button is disabled when Terms & Conditions checkbox is not checked
test('TC_UI_025 - Verify Sign Up button is disabled when Terms & Conditions checkbox is not checked', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'test@example.com');
    await page.fill('[data-testid="username-input"]', 'validuser');
    await page.fill('[data-testid="password-input"]', 'Password1!');
    await page.fill('[data-testid="confirm-password-input"]', 'Password1!');
    // Ensure checkbox is not checked
    await expect(page.locator('[data-testid="terms-checkbox"]')).not.toBeChecked();
    await expect(page.locator('[data-testid="signup-button"]')).toBeDisabled();
});

// TC_UI_026 - Verify Sign Up button becomes enabled when Terms & Conditions checkbox is checked
test('TC_UI_026 - Verify Sign Up button becomes enabled when Terms & Conditions checkbox is checked', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'test@example.com');
    await page.fill('[data-testid="username-input"]', 'validuser');
    await page.fill('[data-testid="password-input"]', 'Password1!');
    await page.fill('[data-testid="confirm-password-input"]', 'Password1!');
    await page.click('[data-testid="terms-checkbox"]'); // Check the checkbox
    await expect(page.locator('[data-testid="signup-button"]')).toBeEnabled();
});

// TC_UI_027 - Verify loading indicator is displayed when Sign Up button is clicked and processing
test('TC_UI_027 - Verify loading indicator is displayed when Sign Up button is clicked and processing', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'test@example.com');
    await page.fill('[data-testid="username-input"]', 'validuser');
    await page.fill('[data-testid="password-input"]', 'Password1!');
    await page.fill('[data-testid="confirm-password-input"]', 'Password1!');
    await page.click('[data-testid="terms-checkbox"]');
    await page.click('[data-testid="signup-button"]');
    await expect(page.locator('[data-testid="loading-indicator"]')).toBeVisible();
});

// TC_UI_028 - Verify Sign Up button is disabled during processing
test('TC_UI_028 - Verify Sign Up button is disabled during processing', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'test@example.com');
    await page.fill('[data-testid="username-input"]', 'validuser');
    await page.fill('[data-testid="password-input"]', 'Password1!');
    await page.fill('[data-testid="confirm-password-input"]', 'Password1!');
    await page.click('[data-testid="terms-checkbox"]');
    await page.click('[data-testid="signup-button"]');
    await expect(page.locator('[data-testid="signup-button"]')).toBeDisabled();
});

// TC_UI_029 - Verify success message is displayed after successful registration
test('TC_UI_029 - Verify success message is displayed after successful registration', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'unique_user@example.com');
    await page.fill('[data-testid="username-input"]', 'uniqueuser');
    await page.fill('[data-testid="password-input"]', 'Password1!');
    await page.fill('[data-testid="confirm-password-input"]', 'Password1!');
    await page.click('[data-testid="terms-checkbox"]');
    await page.click('[data-testid="signup-button"]');
    // Assuming a success message element with data-testid="success-message"
    await expect(page.locator('[data-testid="success-message"]')).toBeVisible();
    await expect(page.locator('[data-testid="success-message"]')).toHaveText('Registration successful! Please check your email for verification.');
});

// TC_UI_030 - Verify redirection to email verification page after successful registration
test('TC_UI_030 - Verify redirection to email verification page after successful registration', async ({ page }) => {
    await page.goto('http://localhost:3000/signup');
    await page.fill('[data-testid="email-input"]', 'another_unique_user@example.com');
    await page.fill('[data-testid="username-input"]', 'anotheruniqueuser');
    await page.fill('[data-testid="password-input"]', 'Password1!');
    await page.fill('[data-testid="confirm-password-input"]', 'Password1!');
    await page.click('[data-testid="terms-checkbox"]');
    await page.click('[data-testid="signup-button"]');
    await page.waitForNavigation(); // Wait for navigation to complete
    await expect(page).toHaveURL('http://localhost:3000/email-verification'); // Assuming this is the verification page URL
});
